[fluffychat]
source = "github"
github = "krille-chan/fluffychat"
use_latest_release = true

[libolm]
source = "gitlab"
gitlab = "matrix-org/olm"
host = "https://gitlab.matrix.org/"
use_max_tag = true

[llama_cpp_for_codeshell]
source = "github"
github = "WisdomShell/llama_cpp_for_codeshell"

[llama_cpp_gg_add-phixtral]
source = "github"
github = "ggerganov/llama.cpp"
branch = "gg/add-phixtral"

[llama_cpp]
source = "github"
github = "ggerganov/llama.cpp"
use_latest_release = true

[nchat]
source = "github"
github = "d99kris/nchat"
use_latest_release = true

[FullTCore]
source = "github"
github = "AirportR/FullTCore"
branch = "meta"

[nitro]
source = "github"
github = "janhq/nitro"
use_latest_release = true

[rwkv_cpp]
source = "github"
github = "saharNooby/rwkv.cpp"

[serenity]
source = "github"
github = "SagerNet/serenity"

[stable-diffusion_cpp]
source = "github"
github = "leejet/stable-diffusion.cpp"

[vaultwarden]
source = "github"
github = "dani-garcia/vaultwarden"
use_latest_release = true