[fluffychat]
source = "github"
github = "krille-chan/fluffychat"
use_latest_release = true

[libolm]
source = "gitlab"
gitlab = "matrix-org/olm"
host = "https://gitlab.matrix.org/"
use_max_tag = true

[nchat]
source = "github"
github = "d99kris/nchat"
use_latest_release = true

[nitro]
source = "github"
github = "janhq/nitro"
use_latest_release = true

[rwkv.cpp]
source = "github"
github = "saharNooby/rwkv.cpp"

[serenity]
source = "github"
github = "SagerNet/serenity"

[vaultwarden]
source = "github"
github = "dani-garcia/vaultwarden"
use_latest_release = true