name: Pack AList Deb

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string

permissions:
  contents: write

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: resources
      - name: Download Binary
        run: |
          wget https://github.com/alist-org/alist/releases/download/${{ inputs.version }}/alist-linux-amd64.tar.gz
          tar -zxvf alist-linux-amd64.tar.gz
          rm -rf alist-linux-amd64.tar.gz
      - name: Prepare
        run: |
          mkdir -p cache/usr/bin/
          mkdir -p cache/var/lib/alist/
          mkdir -p cache/usr/lib/systemd/system/
          chmod +x alist
          mv alist cache/usr/bin/
          mv resources/assets/deb-resources/alist.service cache/usr/lib/systemd/system/
          rm -rf resources
          mkdir -p dist
      - name: Pack amd64 deb
        id: pack_amd64_deb
        uses: jiro4989/build-deb-action@v3
        with:
          package: alist
          package_root: cache/
          maintainer: Xhole
          version: ${{ inputs.version }}
          arch: amd64
          desc: "A file list/WebDAV program that supports multiple storages, powered by Gin and Solidjs."
      - name: Prepare Upload Artifacts
        run: |
          mv ${{ steps.pack_amd64_deb.outputs.file_name }} dist/
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: deb
          path: dist/
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: alist-${{ inputs.version }}
          name: Deb Pack for AList (${{ inputs.version }})
          body: This release contains the officially supported binary of [AList](https://github.com/alist-org/alist) (${{ inputs.version }}), packed for `deb` format.
          files: dist/*
          fail_on_unmatched_files: true