name: Build AppFlowy Supabase Database Tool

on:
  workflow_dispatch:

jobs:
  get_short_commit_hash:
    runs-on: ubuntu-latest
    outputs:
      hash: ${{ steps.short_commit_hash.outputs.short }}
    steps:
      - name: Prepare commit hash
        id: commit_hash
        run: |
          git clone https://github.com/AppFlowy-IO/AppFlowy-Supabase cache --depth 1
          cd cache
          echo "hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          cd ..
          rm -rf cache
      - name: Get short commit hash
        id: short_commit_hash
        uses: prompt/actions-commit-hash@v3
        with:
          commit: ${{ steps.commit_hash.outputs.hash }}
  build:
    needs: get_short_commit_hash
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: AppFlowy-IO/AppFlowy-Supabase
          submodules: recursive
      - name: Build
        run: cargo build --release
      - name: Pack
        run: |
          mkdir dist
          cd target/release
          7z a ../dist/appflowy-supabase-${{ needs.get_short_commit_hash.outputs.hash }}.zip ./*
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: appflowy-win
          path: dist/appflowy-supabase-${{ needs.get_short_commit_hash.outputs.hash }}.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: appflowy-supabase-${{ needs.get_short_commit_hash.outputs.hash }}
          name: Binary build for AppFlowy Supabase Database Tool (${{ needs.get_short_commit_hash.outputs.hash }})
          body: |
            This release contains the x86_64 binary of [AppFlowy Supabase Database Tool](https://github.com/AppFlowy-IO/AppFlowy-Supabase).
          files: dist/*
          fail_on_unmatched_files: true
