name: Setup AppFlowy Database on Supabase

env:
  SUPABASE_DB: ${{ secrets.APPFLOWY_SUPABASE_DB }}
  SUPABASE_DB_USER: ${{ secrets.APPFLOWY_SUPABASE_DB_USER }}
  SUPABASE_DB_PORT: ${{ secrets.APPFLOWY_SUPABASE_DB_PORT }}
  SUPABASE_DB_PASSWORD: ${{ secrets.APPFLOWY_SUPABASE_DB_PASSWORD }}

on:
  workflow_dispatch:
    inputs:
      mode:
        description: Database Migration Mode
        required: true
        default: run
        options:
          - run
          - reset

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: AppFlowy-IO/AppFlowy-Supabase
          submodules: recursive
      - name: Write Supabase Database Credentials
        run: |
          echo "SUPABASE_DB: ${{ env.SUPABASE_DB }}" >> .env.prod
          echo "SUPABASE_DB_USER: ${{ env.SUPABASE_DB_USER }}" >> .env.prod
          echo "SUPABASE_DB_PORT: ${{ env.SUPABASE_DB_PORT }}" >> .env.prod
          echo "SUPABASE_DB_PASSWORD: ${{ env.SUPABASE_DB_PASSWORD }}" >> .env.prod
      - name: Setup Database
        run: cargo run migration ${{ inputs.mode }} ".env.prod"
