name: Build CloudflareWarpSpeedTest

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: peanut996/CloudflareWarpSpeedTest
          submodules: recursive
          ref: ${{ inputs.version }}
      - name: Install Deps
        run: sudo apt-get install zip -y
      - name: Setup Go Environment
        uses: actions/setup-go@v4
        with:
          go-version: stable
          cache: false
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
      - name: Fix some Golang bugs
        run : go clean -modcache
      - name: Build
        run: |
          CGO_ENABLED=1 GOOS=linux GOARCH=386 CC="zig cc -target i386-linux" CXX="zig c++ -target i386-linux" go build -o build/CloudflareWarpSpeedTest -ldflags '-X main.Version=${{ inputs.version }} -s -w' -v
          cd build
          mkdir -p dist
          zip ./dist/CloudflareWarpSpeedTest-${{ inputs.version }}-linux-i686.zip ./CloudflareWarpSpeedTest
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: CloudflareWarpSpeedTest-linux-i696-artifact
          path: build/dist/CloudflareWarpSpeedTest-${{ inputs.version }}-linux-i686.zip
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: CloudflareWarpSpeedTest-${{ inputs.version }}
          name: Binary build for CloudflareWarpSpeedTest (${{ inputs.version }})
          body: This release contains the Linux i686 binary of [CloudflareWarpSpeedTest](https://github.com/peanut996/CloudflareWarpSpeedTest).
          files: build/dist/CloudflareWarpSpeedTest-${{ inputs.version }}-linux-i686.zip
          fail_on_unmatched_files: true
