name: Build FullTCore

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: AirportR/FullTCore
          ref: meta
      - name: Setup Go Environment
        uses: actions/setup-go@v4
      - name: go-mod
        run: go mod tidy
      - name: Build
        run: GOARCH=arm64 GOARM=7 go build -tags with_gvisor -ldflags="-s -w" -o ./output/fulltclash-meta-${{ matrix.os }}-arm64 fulltclash.go
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fulltcore-${{ matrix.os }}-artifact
          path: ./output/*
