name: Build FullTCore ARM64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: AirportR/FullTCore
          ref: meta
      - name: Setup Go Environment
        uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: go-mod
        run: go mod tidy
      - name: Build
        run: GOARCH=arm64 GOARM=7 go build -tags with_gvisor -ldflags="-s -w" -o ./output/fulltclash-meta-ubuntu-20.04-arm64 fulltclash.go
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fulltcore-ubuntu-20.04-arm64-artifact
          path: ./output/*
