name: Build libolm Windows

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string

permissions:
  contents: write

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1
        with:
          windows_compile_environment: msvc
      - name: Install Ninja
        uses: urkle/action-get-ninja@v1
      - name: Checkout
        run: |
          git clone https://gitlab.matrix.org/matrix-org/olm.git . --depth=1 -b ${{ inputs.version }}
          rm -Recurse -Force .git
      - name: Build
        run: |
          cmake . -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release -Bbuild
          cmake --build build --config Release
      - name: Pack
        run: |
          cd build/
          7z a ../libolm-release-v${{ inputs.version }}.zip .
          mv ../libolm-release-v${{ inputs.version }}.zip .
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libolm-win-artifact
          path: |
            build/libolm-release-v${{ inputs.version }}.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: libolm-v${{ inputs.version }}
          name: libolm dll build (v${{ inputs.version }})
          body: |
            This release contains the x86_64 dll of [libolm](https://gitlab.matrix.org/matrix-org/olm).
          files: build/libolm-release-v${{ inputs.version }}.7z
          fail_on_unmatched_files: true
