name: Build libolm Windows

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  OLM_VERSION: 3.2.15

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        run: |
          git clone https://gitlab.matrix.org/matrix-org/olm.git . --depth=1 -b ${{ env.OLM_VERSION }}
      - name: Build
        run: |
          cmake . -Bbuild
          cmake --build build --config Release
      - name: Pack
        run: |
          cd build/Release/
          7z a ../libolm-release-v${{ env.OLM_VERSION }}.7z .
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libolm-win-artifact
          path: |
            build/libolm-release-v${{ env.OLM_VERSION }}.7z
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: libolm-v${{ env.OLM_VERSION }}
          name: libolm dll build (v${{ env.OLM_VERSION }})
          body: |
            This release contains the x86_64 dll of [libolm](https://gitlab.matrix.org/matrix-org/olm).
          files: build/libolm-release-v${{ env.OLM_VERSION }}.7z
          fail_on_unmatched_files: true
