name: Build libolm Windows

on:
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        run: |
          git clone https://gitlab.matrix.org/matrix-org/olm.git . --depth=1 -b 3.2.15
      - name: Build
        run: |
          cmake . -Bbuild
          cmake --build build --config Release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libolm-win-artifact
          path: |
            build/
