name: Build libolm Windows

on:
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        run: |
          git clone https://gitlab.matrix.org/matrix-org/olm.git --depth=1 -b 3.2.15
      - name: Build
        run: |
          cd olm
          cmake . -Bbuild
          cmake --build build
          ls build
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-artifact
          path: |
            olm/build
