name: Build llama.cpp

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: intel-mkl-avx2-linux
            os: ubuntu-latest
            install_deps: |
              wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
              echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
              sudo apt-get update
              sudo apt-get install ccache intel-basekit intel-oneapi-mkl intel-oneapi-mkl-devel ninja-build p7zip-full libcurl4-openssl-dev -y
            pre_build: "source /opt/intel/oneapi/setvars.sh"
            cmake_extra: "-DGGML_BLAS=ON -DGGML_BLAS_VENDOR=Intel10_64lp -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx -DGGML_NATIVE=ON -DGGML_AVX2=ON -DLLAMA_CURL=ON -DLLAMA_LLGUIDANCE=ON"
            zip_name: linux-avx2-intel-mkl-x64

          - name: sycl-avx2-linux
            os: ubuntu-latest
            install_deps: |
              wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
              echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
              sudo apt-get update
              sudo apt-get install ccache intel-basekit intel-oneapi-mkl intel-oneapi-mkl-devel ninja-build p7zip-full libcurl4-openssl-dev -y
            pre_build: "source /opt/intel/oneapi/setvars.sh"
            cmake_extra: "-DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx -DGGML_SYCL=ON -DGGML_AVX2=ON -DLLAMA_CURL=ON -DLLAMA_LLGUIDANCE=ON"
            zip_name: linux-sycl-avx2-x64

          - name: cu132-avx512-linux
            os: ubuntu-latest
            cuda: "13.2.0"
            install_deps: |
              sudo apt-get install ccache ninja-build p7zip-full libcurl4-openssl-dev -y
            cmake_extra: "-DGGML_CUDA=ON -DGGML_AVX512=ON -DGGML_CUDA_FA_ALL_QUANTS=ON -DCMAKE_CUDA_ARCHITECTURES=86 -DLLAMA_CURL=ON -DLLAMA_LLGUIDANCE=ON"
            zip_name: linux-avx512-cuda-cu13.2.0-x64

    runs-on: ${{ matrix.os }}
    steps:
      - name: Install CUDA
        if: matrix.cuda
        uses: MZWNET/cuda-toolkit@master
        with:
          cuda: ${{ matrix.cuda }}
          method: network

      - name: Setup Rust
        run: |
          rustup update stable
          rustup default stable

      - name: Install Deps
        if: matrix.install_deps
        run: ${{ matrix.install_deps }}

      - name: Cache ccache
        uses: actions/cache@v5
        with:
          path: ~/.ccache
          key: ccache-${{ matrix.name }}-${{ inputs.version }}
          restore-keys: ccache-${{ matrix.name }}-

      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: ggml-org/llama.cpp
          submodules: recursive
          ref: ${{ inputs.version }}

      - name: Configure ccache
        run: |
          ccache --set-config=max_size=1G
          ccache --zero-stats

      - name: Build
        shell: bash
        run: |
          mkdir build
          cd build
          ${{ matrix.pre_build || '' }}
          cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DBUILD_SHARED_LIBS=ON ${{ matrix.cmake_extra }}
          cmake --build . --config Release -j $(nproc)

      - name: Pack
        shell: bash
        run: |
          mkdir -p build/dist
          find . -name "*.so" -exec mv {} build/bin/ \;
          cd build/bin/
          7z a ../dist/llama-${{ inputs.version }}-bin-${{ matrix.zip_name }}.zip .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.name }}
          path: build/dist/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: dist/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: llama_cpp-${{ inputs.version }}
          name: Binary build for llama.cpp (${{ inputs.version }})
          body: |
            This release contains the x86_64 binary of [llama.cpp](https://github.com/ggml-org/llama.cpp).
          files: dist/**/*
          fail_on_unmatched_files: true
