name: Build MiniLPA AppImage (Linux Wayland only)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string

permissions:
  contents: write

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: EsimMoe/MiniLPA
          ref: ${{ inputs.version }}
      - name: Checkout JetBrains Setup
        uses: actions/checkout@v5
        with:
          repository: ShiinaSekiu/github-actions-jbr-setup
          ref: jdk
          path: .github/shared_actions/jbr
      - name: Install JetBrains Java Runtime
        uses: ./.github/shared_actions/jbr/setup_jbr21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build Native Executable
        shell: pwsh
        run: |
          ./scripts/Build.ps1 -NativeExecutable -NativeExecutableType app-image -NativeWayland:$true -GithubToken ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MiniLPA-Linux-Wayland-AppImage
          path: build/dist/
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: minilpa-${{ inputs.version }}
          name: Binary(AppImage) Build for MiniLPA (${{ inputs.version }})
          body: This release contains the x86_64 binary (AppImage Format, Linux Wayland Only) of [MiniLPA](https://github.com/EsimMoe/MiniLPA) (${{ inputs.version }}).
          files: build/dist/*
          fail_on_unmatched_files: true