name: Build nchat ARM64

on:
  workflow_dispatch:

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: d99kris/nchat
          ref: v3.60
      - name: Build nchat for Linux ARM64
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: raspios_lite_arm64:latest
          bind_mount_repository: true
          commands: |
            # Install Dependencies
            sudo apt-get install software-properties-common -y
            sudo add-apt-repository ppa:longsleep/golang-backports
            sudo apt-get install ccache cmake build-essential gperf help2man libreadline-dev libssl-dev libncurses-dev libncursesw5-dev ncurses-doc zlib1g-dev libsqlite3-dev libmagic-dev golang-1.21 -y
            mkdir -p build && cd build && cmake .. && make -s
            mkdir build
            make DESTDIR="./build" install
      - run: sudo chmod 777 ./build/build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nchat-arm64-artifact
          path: ./build/build
