name: Build nitro with cuBLAS

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  NITRO_VERSION: 0.3.9

jobs:
  build_cu121:
    runs-on: windows-latest
    steps:
      - name: Install CUDA 12.1
        id: install-cuda
        uses: Jimver/cuda-toolkit@v0.2.11
        with:
          cuda: "12.1.0"
      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1
        with:
          windows_compile_environment: msvc
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: janhq/nitro
          submodules: recursive
          ref: v${{ env.NITRO_VERSION }}
      - name: Install Deps
        run: |
          cmake -S ./nitro_deps -B ./build_deps/nitro_deps
          cmake --build ./build_deps/nitro_deps --config Release
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DRWKV_CUBLAS=ON -DRWKV_AVX512=ON
          make -j $(%NUMBER_OF_PROCESSORS%)
      - name: Pack
        run: |
          cd build/Release
          cp ..\..\build_deps\_install\bin\zlib.dll .
          7z a ..\dist\nitro-${{ env.NITRO_VERSION }}-win-amd64-cuda-12-1-avx512.7z .
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cu121
          path: build/dist/nitro-${{ env.NITRO_VERSION }}-win-amd64-cuda-12-1-avx512.7z
  release:
    runs-on: ubuntu-latest
    needs: build_cu121
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: |
            dist/
      - name: Prepare Release
        run: |
          cd dist
          mv -f cu121/* .
          rm -rf cu121
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nitro-v${{ env.NITRO_VERSION }}
          name: Binary build for nitro (v${{ env.NITRO_VERSION }})
          body: |
            This release contains the x86_64 binary (Windows version) of [nitro](https://github.com/janhq/nitro).

            Please note that I only build for AVX512 & cuBLAS & CUDA v12.1, using VS2022 BuildTools.
          files: dist/*
          fail_on_unmatched_files: true
