name: Build serenity

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup Go Environment
        uses: actions/setup-go@v4
      - name: Build
        run: go install -v -tags with_acme github.com/sagernet/serenity/cmd/serenity@latest
      - name: Export artifactPath
        run: echo "artifactPath=$(go env GOPATH)\bin\serenity.exe" >> $GITHUB_ENV
      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: serenity-artifact
          path: ${{ env.artifactPath }}
