name: Build stable-diffusion.cpp

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: openblas-avx2-linux
            os: ubuntu-latest
            install_deps: |
              sudo apt-get update
              sudo apt-get install ccache ninja-build libopenblas-dev p7zip-full -y
            cmake_extra: "-DGGML_BLAS=ON -DGGML_BLAS_VENDOR=OpenBLAS -DGGML_AVX2=ON"
            zip_name: linux-openblas-avx2-x64

          - name: sycl-avx2-linux
            os: ubuntu-latest
            install_deps: |
              wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
              echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
              sudo apt-get update
              sudo apt-get install ccache intel-basekit intel-oneapi-mkl intel-oneapi-mkl-devel ninja-build p7zip-full -y
            pre_build: "source /opt/intel/oneapi/setvars.sh"
            cmake_extra: "-DSD_SYCL=ON -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx -DGGML_AVX2=ON"
            zip_name: linux-sycl-avx2-x64

          - name: cu130-avx512-linux
            os: ubuntu-latest
            cuda: "13.0.1"
            install_deps: sudo apt-get install ccache p7zip-full ninja-build -y
            cmake_extra: "-DSD_CUDA=ON -DCMAKE_CUDA_ARCHITECTURES=86 -DSD_FAST_SOFTMAX=ON -DGGML_AVX512=ON"
            zip_name: linux-avx512-cublas-cu130-x64

          - name: cu129-avx512-win
            os: windows-latest
            cuda: "12.9.1"
            cuda_sub_packages: '["nvcc", "cudart", "cublas", "cublas_dev", "thrust", "visual_studio_integration"]'
            cmake_extra: "-DSD_CUDA=ON -DCMAKE_CUDA_ARCHITECTURES=86 -DSD_FAST_SOFTMAX=ON -DGGML_AVX512=ON"
            zip_name: win-avx512-cublas-cu129-x64

          - name: metal-macos
            os: macos-latest
            install_deps: brew install ccache ninja libomp 7zip
            cmake_extra: >-
              -DCMAKE_OSX_ARCHITECTURES="arm64" -DSD_METAL=ON -DGGML_METAL_USE_BF16=ON
              -DGGML_METAL_EMBED_LIBRARY=ON -DCMAKE_INSTALL_RPATH='@loader_path'
              -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON -DGGML_RPC=ON
              -DOpenMP_ROOT=$(brew --prefix libomp)
            zip_name: macos-metal-arm64

    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup VS Dev Environment
        if: runner.os == 'Windows'
        uses: seanmiddleditch/gha-setup-vsdevenv@v5

      - name: Install CUDA
        if: matrix.cuda && !matrix.cuda_sub_packages
        uses: MZWNET/cuda-toolkit@master
        with:
          cuda: ${{ matrix.cuda }}
          method: network

      - name: Install CUDA
        if: matrix.cuda && matrix.cuda_sub_packages
        uses: MZWNET/cuda-toolkit@master
        with:
          cuda: ${{ matrix.cuda }}
          method: network
          sub-packages: ${{ matrix.cuda_sub_packages }}

      - name: Setup ccache (Windows)
        if: runner.os == 'Windows'
        uses: Chocobo1/setup-ccache-action@v1
        with:
          windows_compile_environment: msvc

      - name: Install Ninja (Windows)
        if: runner.os == 'Windows'
        uses: urkle/action-get-ninja@v1

      - name: Install Deps
        if: matrix.install_deps
        run: ${{ matrix.install_deps }}

      - name: Cache ccache (Unix)
        if: runner.os != 'Windows'
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ccache-${{ matrix.name }}-${{ inputs.version }}
          restore-keys: ccache-${{ matrix.name }}-

      - name: Cache ccache (Windows)
        if: runner.os == 'Windows'
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\ccache
          key: ccache-${{ matrix.name }}-${{ inputs.version }}
          restore-keys: ccache-${{ matrix.name }}-

      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: leejet/stable-diffusion.cpp
          ref: ${{ inputs.version }}
          submodules: recursive

      - name: Parse semver
        id: semver
        shell: bash
        run: |
          VERSION=$(echo "${{ inputs.version }}" | cut -d'-' -f2)
          echo "version=0.0.${VERSION}"
          echo "version=0.0.${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Configure ccache
        shell: bash
        run: |
          ccache --set-config=max_size=1G
          ccache --zero-stats

      - name: Build
        shell: bash
        run: |
          mkdir build
          cd build
          ${{ matrix.pre_build || '' }}
          cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DSD_BUILD_SHARED_LIBS=ON -DSD_BUILD_SHARED_GGML_LIB=ON -DSDCPP_BUILD_VERSION=${{ steps.semver.outputs.version }} ${{ matrix.cmake_extra }}
          cmake --build . --config Release -j $(nproc 2>/dev/null || sysctl -n hw.logicalcpu)

      - name: Pack
        shell: bash
        run: |
          mkdir -p build/dist
          cd build/bin/
          7z a ../dist/sd-${{ inputs.version }}-bin-${{ matrix.zip_name }}.zip .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.name }}
          path: build/dist/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: dist/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: sd-${{ inputs.version }}
          name: Binary build for stable-diffusion.cpp (${{ inputs.version }})
          body: |
            This release contains the x86_64 binary of [stable-diffusion.cpp](https://github.com/leejet/stable-diffusion.cpp).
          files: dist/**/*
          fail_on_unmatched_files: true
