name: Build TWRP (Gionee F103s)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free space
        uses: rokibhasansagar/slimhub_actions@main
        with:
          retain: docker_buildkit
      - name: List free spaces
        run: |
            df -ha
      - name: Test docker
        run: |
          docker run --rm ubuntu:bionic /bin/bash -c 'df -ha && cat /etc/os-release && dd if=/dev/zero of=testfile bs=1G count=50 && df -ha'