name: Build UI-TARS Desktop Linux Version

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  get_short_commit_hash:
    runs-on: ubuntu-latest
    outputs:
      hash: ${{ steps.short_commit_hash.outputs.short }}
    steps:
      - name: Prepare commit hash
        id: commit_hash
        run: |
          git clone https://github.com/mzwing/UI-TARS-desktop.git -b linux cache --depth 1
          cd cache
          echo "hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          cd ..
          rm -rf cache
      - name: Get short commit hash
        id: short_commit_hash
        uses: prompt/actions-commit-hash@v3
        with:
          commit: ${{ steps.commit_hash.outputs.hash }}
  build:
    needs: get_short_commit_hash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: mzwing/UI-TARS-desktop
          submodules: recursive
          ref: linux
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: latest
          check-latest: true
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Build
        run: |
          pnpm run build
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ui-tars-desktop-${{ needs.get_short_commit_hash.outputs.hash }}
          name: Binary Build for UI-TARS Desktop (${{ needs.get_short_commit_hash.outputs.hash }})
          body: This release contains the x86_64 binary of [UI-TARS Desktop](https://github.com/bytedance/UI-TARS-desktop)(Merged bytedance/UI-TARS-desktop#45) (${{ needs.get_short_commit_hash.outputs.hash }}).
          files: out/make/deb/**/*
          fail_on_unmatched_files: true