name: Build vaultwarden Binary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: |
          wget https://raw.githubusercontent.com/jjlin/docker-image-extract/main/docker-image-extract
          chmod +x docker-image-extract
          mkdir x86_64
          mkdir armv6
          mkdir armv7
          mkdir arm64
      - name: Pull & Extract
        run: |
          cd x86_64
          ../docker-image-extract vaultwarden/server:latest
          cd ../armv6
          ../docker-image-extract -p linux/arm/v6 vaultwarden/server:latest
          cd ../armv7
          ../docker-image-extract -p linux/arm/v7 vaultwarden/server:latest
          cd ../arm64
          ../docker-image-extract -p linux/arm64 vaultwarden/server:latest
      - name: Clean
        run: |
          mkdir dist
          mkdir dist/x86_64
          mkdir dist/armv6
          mkdir dist/armv7
          mkdir dist/arm64
          cp -r output/x86_64/vaultwarden dist/x86_64
          cp -r output/armv6/vaultwarden dist/armv6
          cp -r output/armv7/vaultwarden dist/armv7
          cp -r output/arm64/vaultwarden dist/arm64
          cp -r output/x86_64/web-vault dist/x86_64
          cp -r output/armv6/web-vault dist/armv6
          cp -r output/armv7/web-vault dist/armv7
          cp -r output/arm64/web-vault dist/arm64
      - name: Pack
        run: |
          cd dist/x86_64/
          tar -zcvf ../../vaultwarden-x86_64-binary.tar.gz .
          cd ../armv6/
          tar -zcvf ../../vaultwarden-armv6-binary.tar.gz .
          cd ../armv7/
          tar -zcvf ../../vaultwarden-armv7-binary.tar.gz .
          cd ../arm64/
          tar -zcvf ../../vaultwarden-arm64-binary.tar.gz .
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vaultwarden-artifact
          path: |
            vaultwarden-x86_64-binary.tar.gz
            vaultwarden-armv6-binary.tar.gz
            vaultwarden-armv7-binary.tar.gz
            vaultwarden-arm64-binary.tar.gz
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: vaultwarden-bin
          name: vaultwarden Binary
          body: This release contains the officially supported binary of [vaultwarden](https://github.com/dani-garcia/vaultwarden), extracted from official docker image.
          files: |
            vaultwarden-x86_64-binary.tar.gz
            vaultwarden-armv6-binary.tar.gz
            vaultwarden-armv7-binary.tar.gz
            vaultwarden-arm64-binary.tar.gz
          fail_on_unmatched_files: true
