name: Build whisper.cpp

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string

permissions:
  contents: write

jobs:
  ersion:
    runs-on: ubuntu-latest
    outputs:
      ersion: ${{ steps.ersion.outputs.ersion }}
    steps:
      - name: Process Version for No v Prefix
        id: ersion
        shell: python
        run: |
          import subprocess
          version = "${{ inputs.version }}"
          ersion = version.replace("v", "")
          subprocess.run(f'echo ersion={ersion} >> $GITHUB_OUTPUT', shell=True, check=True)

  build:
    needs: ersion
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: sycl-avx2-linux
            os: ubuntu-latest
            install_deps: |
              wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
              echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
              sudo apt-get update
              sudo apt-get install ccache intel-basekit intel-oneapi-mkl intel-oneapi-mkl-devel ninja-build p7zip-full -y
            pre_build: "source /opt/intel/oneapi/setvars.sh"
            cmake_extra: "-DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx -DGGML_SYCL=ON -DGGML_AVX2=ON"
            zip_name: linux-avx2-sycl-x64

          - name: cu132-avx512-linux
            os: ubuntu-latest
            cuda: "13.2.0"
            install_deps: sudo apt-get install ccache ninja-build p7zip-full -y
            cmake_extra: "-DGGML_CUDA=ON -DGGML_AVX512=ON -DGGML_CUDA_FA_ALL_QUANTS=ON -DCMAKE_CUDA_ARCHITECTURES=86"
            zip_name: linux-avx512-cuda-cu13.2.0-x64

    runs-on: ${{ matrix.os }}
    steps:
      - name: Install CUDA
        if: matrix.cuda
        uses: MZWNET/cuda-toolkit@master
        with:
          cuda: ${{ matrix.cuda }}
          method: network

      - name: Install Deps
        if: matrix.install_deps
        run: ${{ matrix.install_deps }}

      - name: Cache ccache
        uses: actions/cache@v5
        with:
          path: ~/.ccache
          key: ccache-${{ matrix.name }}-${{ inputs.version }}
          restore-keys: ccache-${{ matrix.name }}-

      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: ggml-org/whisper.cpp
          submodules: recursive
          ref: ${{ inputs.version }}

      - name: Configure ccache
        run: |
          ccache --set-config=max_size=1G
          ccache --zero-stats

      - name: Build
        shell: bash
        run: |
          mkdir build
          cd build
          ${{ matrix.pre_build || '' }}
          cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DBUILD_SHARED_LIBS=ON ${{ matrix.cmake_extra }}
          cmake --build . --config Release -j $(nproc)

      - name: Pack
        shell: bash
        run: |
          mkdir -p build/dist
          mv build/src/libwhisper.so.${{ needs.ersion.outputs.ersion }} build/bin/libwhisper.so
          cd build/bin/
          7z a ../dist/whisper-${{ inputs.version }}-bin-${{ matrix.zip_name }}.zip .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.name }}
          path: build/dist/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: dist/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: whisper_cpp-${{ inputs.version }}
          name: Binary build for whisper.cpp (${{ inputs.version }})
          body: |
            This release contains the x86_64 binary of [whisper.cpp](https://github.com/ggml-org/whisper.cpp).
          files: dist/**/*
          fail_on_unmatched_files: true
